-- Custom Ships ----------
model = ModelData()
model:setName("sphere_1")
model:setMesh("Artifacts/Artifact2.obj")
model:setTexture("Artifacts/electric_sphere_texture_g.png")
model:setScale(5)
model:setRadius(100)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)
model :addEngineEmitter(-15, 15, 0,  0.2, 1.0, 0.2, 6.0)
model :addEngineEmitter(-15, -15, 0,  0.2, 1.0, 0.2, 6.0)

-- ███████ ████████  █████  ████████ ██  ██████  ███    ██ ███████
-- ██         ██    ██   ██    ██    ██ ██    ██ ████   ██ ██
-- ███████    ██    ███████    ██    ██ ██    ██ ██ ██  ██ ███████
--      ██    ██    ██   ██    ██    ██ ██    ██ ██  ██ ██      ██
-- ███████    ██    ██   ██    ██    ██  ██████  ██   ████ ███████

-- SolCommand Stations ----------
model = ModelData()
model:setName("kece")
model:setMesh("SC-Stations/kece.obj")
model:setTexture("SC-Stations/kece.jpg")
model:setRenderOffset(50, 30, 0)
model:setScale(8)
model:setRadius(1700)
model:setCollisionBox(1820, 1430)

model = ModelData()
model:setName("kono")
model:setMesh("SC-Stations/kono.obj")
model:setTexture("SC-Stations/kono.jpg")
model:setRenderOffset(0, 0, -50)
model:setScale(8)
model:setRadius(2000)
model:setCollisionBox(2015, 1430)

model = ModelData()
model:setName("mal")
model:setMesh("SC-Stations/mal.obj")
model:setTexture("SC-Stations/mal.jpg")
model:setRenderOffset(0, 0, 28)
model:setScale(6)
model:setRadius(760)
model:setCollisionBox(780, 680)

model = ModelData()
model:setName("serenity")
model:setMesh("SC-Stations/serenity.obj")
model:setTexture("SC-Stations/serenity.jpg")
model:setRenderOffset(0, 0, -120)
model:setScale(6)
model:setRadius(1050)
model:setCollisionBox(1300, 1430)

model = ModelData()
model:setName("comm-hub")
model:setMesh("SC-Stations/comm-hub.obj")
model:setTexture("SC-Stations/comm-hub.jpg")
model:setRenderOffset(0, 0, 0)
model:setScale(3)
model:setRadius(300)
model:setCollisionBox(244, 244)

model = ModelData()
model:setName("eezo")
model:setMesh("SC-Stations/eezo.obj")
model:setTexture("SC-Stations/eezo.jpg")
model:setRenderOffset(-60, 0, 0)
model:setScale(4)
model:setRadius(1000)
model:setCollisionBox(1040, 650)

model = ModelData()
model:setName("derelict")
model:setMesh("SC-Stations/derelict.obj")
model:setTexture("SC-Stations/derelict.jpg")
model:setRenderOffset(-10, 5, -40)
model:setScale(16)
model:setRadius(1200)
model:setCollisionBox(1000, 1000)

model = ModelData()
model:setName("heresy-r")
model:setMesh("SC-Stations/heresy.obj")
model:setTexture("SC-Stations/heresy-r.png")
model:setRenderOffset(-100, 50, 50)
model:setScale(1.2)
model:setRadius(130)
model:setCollisionBox(260, 260)

model = ModelData()
model:setName("heresy-g")
model:setMesh("SC-Stations/heresy.obj")
model:setTexture("SC-Stations/heresy-g.png")
model:setRenderOffset(-100, 50, 50)
model:setScale(5)
model:setRadius(500)
model:setCollisionBox(600, 600)

model = ModelData()
model:setName("paratka")
model:setMesh("SC-Stations/paratka.obj")
model:setTexture("SC-Stations/paratka.jpg")
model:setRenderOffset(0, 0, 0)
model:setScale(4)
model:setRadius(300)
model:setCollisionBox(400, 400)

model = ModelData()
model:setName("mass-accelerator")
model:setMesh("SC-Stations/mass-accelerator.obj")
model:setTexture("SC-Stations/mass-accelerator.jpg")
model:setRenderOffset(0, 0, 0)
model:setScale(4)
model:setRadius(300)
model:setCollisionBox(400, 400)

model = ModelData()
model:setName("wormhole-generator")
model:setMesh("SC-Stations/wormhole-generator.obj")
model:setTexture("SC-Stations/wormhole-generator.jpg")
model:setRenderOffset(0, 0, 0)
model:setScale(4)
model:setRadius(300)
model:setCollisionBox(400, 400)

-- ███████ ██  ██████  ██   ██ ████████ ███████ ██████  ███████
-- ██      ██ ██       ██   ██    ██    ██      ██   ██ ██
-- █████   ██ ██   ███ ███████    ██    █████   ██████  ███████
-- ██      ██ ██    ██ ██   ██    ██    ██      ██   ██      ██
-- ██      ██  ██████  ██   ██    ██    ███████ ██   ██ ███████

-- SolCommand Fighters ----------
model = ModelData()
model:setName("Swordfish")
model:setMesh("SC-Ship-Pack-2010/swordfish.obj")
model:setTexture("SC-Ship-Pack-2010/swordfish.jpg")
model:setScale(1.33)
model:setRadius(50)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-14, 8, 0.0, 0.5, 0.6, 1.0, 6.0)
model:addEngineEmitter(-14, -8, 0.0, 0.5, 0.6, 1.0, 6.0)

model = ModelData()
model:setName("CobraFighter")
model:setMesh("SC-Ship-Pack-2010/cobra-fighter.obj")
model:setTexture("SC-Ship-Pack-2010/cobra-fighter.jpg")
model:setScale(3)
model:setRadius(50)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-14, 8, 0.0, 0.5, 0.6, 1.0, 6.0)
model:addEngineEmitter(-14, -8, 0.0, 0.5, 0.6, 1.0, 6.0)

model = ModelData()
model:setName("CobraBomber")
model:setMesh("SC-Ship-Pack-2010/cobra-bomber.obj")
model:setTexture("SC-Ship-Pack-2010/cobra-bomber.jpg")
model:setScale(3)
model:setRadius(60)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-14, 8, 0.0, 0.5, 0.6, 1.0, 6.0)
model:addEngineEmitter(-14, -8, 0.0, 0.5, 0.6, 1.0, 6.0)

model = ModelData()
model:setName("CobraInterceptor")
model:setMesh("SC-Ship-Pack-2010/cobra-interceptor.obj")
model:setTexture("SC-Ship-Pack-2010/cobra-interceptor.jpg")
model:setScale(3)
model:setRadius(42)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-14, 8, 0.0, 0.5, 0.6, 1.0, 6.0)
model:addEngineEmitter(-14, -8, 0.0, 0.5, 0.6, 1.0, 6.0)

model = ModelData()
model:setName("Blackbird")
model:setMesh("SC-Ship-Pack-2010/blackbird-r.obj")
model:setTexture("SC-Ship-Pack-2010/blackbird1.jpg")
model:setScale(0.4)
model:setRadius(42)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-120, 40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-120, -40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-120, 0, 15, 0.5, 0.6, 1.0, 18.0)

model = ModelData()
model:setName("Blackbird-C")
model:setMesh("SC-Ship-Pack-2010/blackbird-r.obj")
model:setTexture("SC-Ship-Pack-2010/blackbird-c.jpg")
model:setScale(0.4)
model:setRadius(42)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-120, 40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-120, -40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-120, 0, 15, 0.5, 0.6, 1.0, 18.0)

model = ModelData()
model:setName("Kanara")
model:setMesh("SC-Ship-Pack-2010/kanara.obj")
model:setTexture("SC-Ship-Pack-2010/kanara.jpg")
model:setScale(0.4)
model:setRadius(42)
model:addTubePosition(-8, -10, 0)
model:addTubePosition(-8, 10, 0)
model:addTubePosition(-14, 0, 0)
model:addEngineEmitter(-60, 40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-60, -40, 5, 0.5, 0.6, 1.0, 18.0)
model:addEngineEmitter(-50, 15, 5, 0.5, 0.6, 1.0, 12.0)
model:addEngineEmitter(-50, -15, 5, 0.5, 0.6, 1.0, 12.0)

-- ███████ ██████  ██  ██████   █████  ████████ ███████ ███████
-- ██      ██   ██ ██ ██       ██   ██    ██    ██      ██
-- █████   ██████  ██ ██   ███ ███████    ██    █████   ███████
-- ██      ██   ██ ██ ██    ██ ██   ██    ██    ██           ██
-- ██      ██   ██ ██  ██████  ██   ██    ██    ███████ ███████

-- SolCommand Frigates ----------
model = ModelData()
model:setName("Morena")
model:setMesh("SC-Ship-Pack-2010/morena.obj")
model:setTexture("SC-Ship-Pack-2010/morena.png")
model:setScale(0.8)
model:setRadius(140)
model:setCollisionBox(264, 100)
model:addTubePosition(100, 45, 0)
model:addTubePosition(100,-45, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-200, 45, 0, 0.5, 0.6, 1.0, 25)
model:addEngineEmitter(-200, -45, 0, 0.5, 0.6, 1.0, 25)

model = ModelData()
model:setName("Morena-C")
model:setMesh("SC-Ship-Pack-2010/morena.obj")
model:setTexture("SC-Ship-Pack-2010/morena-c.png")
model:setScale(1)
model:setRadius(140)
model:setCollisionBox(264, 100)
model:addTubePosition(100, 45, 0)
model:addTubePosition(100,-45, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-200, 45, 0, 0.5, 0.6, 1.0, 20)
model:addEngineEmitter(-200, -45, 0, 0.5, 0.6, 1.0, 20)

model = ModelData()
model:setName("Oltenia")
model:setMesh("SC-Ship-Pack-2010/oltenia.obj")
model:setTexture("SC-Ship-Pack-2010/oltenia.png")
model:setScale(1)
model:setRadius(140)
model:setCollisionBox(264, 100)
model:addTubePosition(100, 45, 0)
model:addTubePosition(100,-45, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-200, 45, 0, 0.5, 0.6, 1.0, 25)
model:addEngineEmitter(-200, -45, 0, 0.5, 0.6, 1.0, 25)

model = ModelData()
model:setName("Mae Arae")
model:setMesh("SC-Ship-Pack-2010/mae arae.obj")
model:setTexture("SC-Ship-Pack-2010/maearaeCompleteMap.jpg")
model:setScale(1)
model:setRadius(140)
model:setCollisionBox(264, 100)
model:addTubePosition(100, 45, 0)
model:addTubePosition(100,-45, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-200, 45, 0, 0.5, 0.6, 1.0, 25)
model:addEngineEmitter(-200, -45, 0, 0.5, 0.6, 1.0, 25)

--  ██████  ██████  ██████  ██    ██ ███████ ████████ ████████ ███████ ███████
-- ██      ██    ██ ██   ██ ██    ██ ██         ██       ██    ██      ██
-- ██      ██    ██ ██████  ██    ██ █████      ██       ██    █████   ███████
-- ██      ██    ██ ██   ██  ██  ██  ██         ██       ██    ██           ██
--  ██████  ██████  ██   ██   ████   ███████    ██       ██    ███████ ███████

-- SolCommand Corvettes ----------
model = ModelData()
model:setName("MCCV2")
model:setMesh("MCCV2/MCCV-2-r1.obj")
model:setTexture("MCCV2/MCCV-2-T1.png")
model:setSpecular("MCCV2/MCCV-2-S.png")
model:setScale(5)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)
model:addEngineEmitter(-48, 13, 17,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -13, 17,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 26,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 26,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 8,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 8,  1.0, 1.0, 0.2, 6.0)

model = ModelData()
model:setName("MCCV2A")
model:setMesh("MCCV2/MCCV-2-r1.obj")
model:setTexture("MCCV2/MCCV-2-T2.png")
model:setSpecular("MCCV2/MCCV-2-S.png")
model:setScale(5)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)
model:addEngineEmitter(-48, 13, 17,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -13, 17,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 26,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 26,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 8,  1.0, 1.0, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 8,  1.0, 1.0, 0.2, 6.0)

model = ModelData()
model:setName("MCCV2X")
model:setMesh("MCCV2/MCCV-2-r1.obj")
model:setTexture("MCCV2/MCCV-2-T3.png")
model:setSpecular("MCCV2/MCCV-2-SD.png")
model:setScale(5)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)
model:addEngineEmitter(-48, 13, 17,   1.0, 0.2, 0.2, 6.0)
model:addEngineEmitter(-48, -13, 17,  1.0, 0.2, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 26,    1.0, 0.2, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 26,   1.0, 0.2, 0.2, 6.0)
model:addEngineEmitter(-48, 8, 8,     1.0, 0.2, 0.2, 6.0)
model:addEngineEmitter(-48, -8, 8,    1.0, 0.2, 0.2, 6.0)

model = ModelData()
model:setName("Eris")
model:setMesh("SC-Ship-Pack-2010/eris.obj")
model:setTexture("SC-Ship-Pack-2010/eris.jpg")
model:setScale(3)
model:setRadius(480)
model:setCollisionBox(880, 300)
model:addTubePosition(190, 10, 0)
model:addTubePosition(190,-10, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-180, 32, 5, 0.5, 0.6, 1.0, 10)
model:addEngineEmitter(-180, -32, 5, 0.5, 0.6, 1.0, 10)
model:addEngineEmitter(-180, 48, 5, 0.5, 0.6, 1.0, 10)
model:addEngineEmitter(-180, -48, 5, 0.5, 0.6, 1.0, 10)
model:addEngineEmitter(-180, 40, -5, 0.5, 0.6, 1.0, 10)
model:addEngineEmitter(-180, -40, -5, 0.5, 0.6, 1.0, 10)

model = ModelData()
model:setName("Eris-C")
model:setMesh("SC-Ship-Pack-2010/eris.obj")
model:setTexture("SC-Ship-Pack-2010/eris-c.jpg")
model:setScale(2)
model:setRadius(480)
model:setCollisionBox(880, 300)
model:addTubePosition(190, 10, 0)
model:addTubePosition(190,-10, 0)
model:addTubePosition(-180, 0, 0)
model:addEngineEmitter(-180, 32, 5, 0.5, 0.6, 1.0, 8)
model:addEngineEmitter(-180, -32, 5, 0.5, 0.6, 1.0, 8)
model:addEngineEmitter(-180, 48, 5, 0.5, 0.6, 1.0, 8)
model:addEngineEmitter(-180, -48, 5, 0.5, 0.6, 1.0, 8)
model:addEngineEmitter(-180, 40, -5, 0.5, 0.6, 1.0, 8)
model:addEngineEmitter(-180, -40, -5, 0.5, 0.6, 1.0, 8)

model = ModelData()
model:setName("Ghost")
model:setMesh("SC-Ship-Pack-2010/ghost_obj.obj")
model:setTexture("SC-Ship-Pack-2010/ghostmap_png.png")
model:setScale(1)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)


model = ModelData()
model:setName("Anna-V")
model:setMesh("SC-Ship-Pack-2010/Anna-V/Anna-V.obj")
model:setTexture("SC-Ship-Pack-2010/Anna-V/ship_hull18.jpg")
model:setScale(2.5)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)

model = ModelData()
model:setName("Lancelot")
model:setMesh("Tadeo/Lancelot.obj")
model:setTexture("Tadeo/Textures/Lancelot_Hull1_Base.png")
model:setScale(8)
model:setRadius(500)
model:setCollisionBox(1000, 300)
model:addTubePosition(0, 0, 0)
model:addBeamPosition(0, 0, 0)

-- ██████  ██████  ███████  █████  ██████  ███    ██  █████  ██    ██  ██████  ██   ██ ████████ ███████
-- ██   ██ ██   ██ ██      ██   ██ ██   ██ ████   ██ ██   ██ ██    ██ ██       ██   ██    ██    ██
-- ██   ██ ██████  █████   ███████ ██   ██ ██ ██  ██ ███████ ██    ██ ██   ███ ███████    ██    ███████
-- ██   ██ ██   ██ ██      ██   ██ ██   ██ ██  ██ ██ ██   ██ ██    ██ ██    ██ ██   ██    ██         ██
-- ██████  ██   ██ ███████ ██   ██ ██████  ██   ████ ██   ██  ██████   ██████  ██   ██    ██    ███████

-- SolCommand Dreadnaughts ----------
model = ModelData()
model:setName("Ender Battlecruiser")
model:setMesh("Ender/Ender Battlecruiser.obj")
model:setTexture("Ender/bc-darker.jpg")
model:setScale(5)
model:setRadius(1000)
model:setCollisionBox(2000, 800)
model:addBeamPosition(66, -71, 12)
model:addBeamPosition(66, -71, -12)
model:addBeamPosition(66,  71, 12)
model:addBeamPosition(66,  71, -12)
model:addBeamPosition(-32, -71, 12)
model:addBeamPosition(-32, -71, -12)
model:addBeamPosition(-32,  71, 12)
model:addBeamPosition(-32,  71, -12)
model:addBeamPosition(-112, -71, 12)
model:addBeamPosition(-112, -71, -12)
model:addBeamPosition(-112,  71, 12)
model:addBeamPosition(-112,  71, -12)
model:addBeamPosition(160,  -20, 0)
model:addBeamPosition(160,  20, 0)
model:addEngineEmitter(-180, -30, 1.2,  0.2, 0.2, 1.0, 30.0)
model:addEngineEmitter(-180,  30, 1.2,  0.2, 0.2, 1.0, 30.0)

model = ModelData()
model:setName("Mjolnir Titan")
model:setMesh("SC-Misc/titan.obj")
model:setTexture("SC-Misc/titan.png")
model:setScale(12)
model:setRadius(2000)
model:setCollisionBox(2000, 700)
model:addBeamPosition(120, 0, 0)
model:addEngineEmitter(-120, -15, 1.5,  1.0, 0.2, 0.2, 10.0)
model:addEngineEmitter(-120,  15, 1.5,  1.0, 0.2, 0.2, 10.0)
model:addEngineEmitter(-120, -10, 11.5,  1.0, 0.2, 0.2, 10.0)
model:addEngineEmitter(-120,  10, 11.5,  1.0, 0.2, 0.2, 10.0)
model:addEngineEmitter(-120, -10, -8.3,  1.0, 0.2, 0.2, 10.0)
model:addEngineEmitter(-120,  10, -8.3,  1.0, 0.2, 0.2, 10.0)

-- ███    ███ ██ ███████  ██████
-- ████  ████ ██ ██      ██
-- ██ ████ ██ ██ ███████ ██
-- ██  ██  ██ ██      ██ ██
-- ██      ██ ██ ███████  ██████

-- SolCommand Misc ----------
model = ModelData()
model:setName("shield_generator")
model:setRadius(150)
model:setScale(3)
model:setMesh("SC-Misc/Shield bubble generator.obj")
model:setTexture("SC-Misc/Shield bubble generator.jpg")
model:setSpecular("SC-Misc/Shield bubble generator specular.jpg")

model = ModelData()
model:setName("sensor-buoy")
model:setRadius(150)
model:setScale(2)
model:setMesh("SC-Misc/sensor-buoy.obj")
model:setTexture("SC-Misc/sensor-buoy.jpg")

ModelData():setName("artifact1"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact1.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact2"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact2.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact3"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact3.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact4"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact4.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact5"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact5.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact6"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact6.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact7"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact7.obj"):setTexture("electric_sphere_texture.png")
ModelData():setName("artifact8"):setScale(3):setRadius(50):setMesh("Artifacts/Artifact8.obj"):setTexture("electric_sphere_texture.png")

-- BC Ship Data

for _, color in ipairs({"Beige", "Black", "Blue", "Green", "Grey"}) do
    model = ModelData()
    model:setName("HeliconCorpBastionClassDestroyer" .. color)
    model:setMesh("HeliconCorpBastionClassDestroyer/HeliconCorpBastionClassDestroyer.obj")
    model:setTexture("HeliconCorpBastionClassDestroyer/HeliconCorpBastionClassDestroyer"..color.."Albedo.png")
    model:setSpecular("HeliconCorpBastionClassDestroyer/HeliconCorpBastionClassDestroyerSpecular.png")
    model:setIllumination("HeliconCorpBastionClassDestroyer/HeliconCorpBastionClassDestroyerIllumination.png")
    model:setScale(0.5)
    model:setRadius(150)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)

    model = ModelData()
    model:setName("HeliconCorpBulkClassFrigate" .. color)
    model:setMesh("HeliconCorpBulkClassFrigate/HeliconCorpBulkClassFrigate.obj")
    model:setTexture("HeliconCorpBulkClassFrigate/HeliconCorpBulkClassFrigate"..color.."Albedo.png")
    model:setSpecular("HeliconCorpBulkClassFrigate/HeliconCorpBulkClassFrigateSpecular.png")
    model:setIllumination("HeliconCorpBulkClassFrigate/HeliconCorpBulkClassFrigateIllumination.png")
    model:setScale(1)
    model:setRadius(150)

    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("HeliconCorpBruteClassFrigate" .. color)
    model:setMesh("HeliconCorpBruteClassFrigate/HeliconCorpBruteClassFrigate.obj")
    model:setTexture("HeliconCorpBruteClassFrigate/HeliconCorpBruteClassFrigate"..color.."Albedo.png")
    model:setSpecular("HeliconCorpBruteClassFrigate/HeliconCorpBruteClassFrigateSpecular.png")
    model:setIllumination("HeliconCorpBruteClassFrigate/HeliconCorpBruteClassFrigateIllumination.png")
    model:setScale(1)
    model:setRadius(150)
    model:addTubePosition(1.4, 0, 0.06)
    model:addTubePosition(0.3, 0.5, 0.06)
    model:addTubePosition(0.3,-0.5, 0.06)
    model:addEngineEmitter(-1, 0.54, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1,-0.54, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("HeliconCorpChroneClassBattlecruiser" .. color)
    model:setMesh("HeliconCorpChroneClassBattlecruiser/HeliconCorpChroneClassBattlecruiserHull.obj")
    model:setTexture("HeliconCorpChroneClassBattlecruiser/HeliconCorpChroneClassBattlecruiser"..color.."Albedo.png")
    model:setSpecular("HeliconCorpChroneClassBattlecruiser/HeliconCorpChroneClassBattlecruiserSpecular.png")
    model:setIllumination("HeliconCorpChroneClassBattlecruiser/HeliconCorpChroneClassBattlecruiserIllumination.png")
    model:setScale(0.6)
    model:setRadius(250)
    model:addBeamPosition(1.15, 0.13, -0.03)
    model:addBeamPosition(1.15,-0.13, -0.03)
    model:addEngineEmitter(-0.2, 0.44, -0.03,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-0.2,-0.44, -0.03,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("HeliconCorpNorasClassCruiser" .. color)
    model:setMesh("HeliconCorpNorasClassCruiser/HeliconCorpNorasClassCruiserHull.obj")
    model:setTexture("HeliconCorpNorasClassCruiser/HeliconCorpNorasClassCruiser"..color.."Albedo.png")
    model:setSpecular("HeliconCorpNorasClassCruiser/HeliconCorpNorasClassCruiserSpecular.png")
    model:setIllumination("HeliconCorpNorasClassCruiser/HeliconCorpNorasClassCruiserIllumination.png")
    model:setScale(0.5)
    model:setRadius(200)

    model:addEngineEmitter(-1.4, 0.4, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4, 0.0, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4,-0.4, 0.0,  0.5, 0.5, 1.0, 0.6)

    model = ModelData()
    model:setName("HeliconCorpValenClassCarrier" .. color)
    model:setMesh("HeliconCorpValenClassCarrier/HeliconCorpValenClassCarrier.obj")
    model:setTexture("HeliconCorpValenClassCarrier/HeliconCorpValenClassCarrier"..color.."Albedo.png")
    model:setSpecular("HeliconCorpValenClassCarrier/HeliconCorpValenClassCarrierSpecular.png")
    model:setIllumination("HeliconCorpValenClassCarrier/HeliconCorpValenClassCarrierIllumination.png")
    model:setScale(1)
    model:setRadius(300)

    model:addEngineEmitter(-1.67, 0.1, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-1.67,-0.1, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("HeliconCorpHaydronClassBattleship" .. color)
    model:setMesh("HeliconCorpHaydronClassBattleship/HeliconCorpHaydronClassBattleship.obj")
    model:setTexture("HeliconCorpHaydronClassBattleship/HeliconCorpHaydronClassBattleship"..color.."Albedo.png")
    model:setSpecular("HeliconCorpHaydronClassBattleship/HeliconCorpHaydronClassBattleshipSpecular.png")
    model:setIllumination("HeliconCorpHaydronClassBattleship/HeliconCorpHaydronClassBattleshipIllumination.png")
    model:setScale(1)
    model:setRadius(300)

    model:addEngineEmitter(-1.3, 0.22, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3, 0.00, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3,-0.22, 0.15,  0.5, 0.5, 1.0, 0.3)

    model = ModelData()
    model:setName("HeliconCorpBomberHB22" .. color)
    model:setMesh("HeliconCorpBomberHB22/HeliconCorpBomberHB22Hull.obj")
    model:setTexture("HeliconCorpBomberHB22/HeliconCorpBomberHB22"..color.."Albedo.png")
    model:setSpecular("HeliconCorpBomberHB22/HeliconCorpBomberHB22Specular.png")
    model:setIllumination("HeliconCorpBomberHB22/HeliconCorpBomberHB22Illumination.png")
    model:setScale(2)
    model:setRadius(60)

    model:addEngineEmitter(-0.65, 0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.65,-0.70, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("HeliconCorpFighterHF13" .. color)
    model:setMesh("HeliconCorpFighterHF13/HeliconCorpFighterHF13Hull.obj")
    model:setTexture("HeliconCorpFighterHF13/HeliconCorpFighterHF13"..color.."Albedo.png")
    model:setSpecular("HeliconCorpFighterHF13/HeliconCorpFighterHF13Specular.png")
    model:setIllumination("HeliconCorpFighterHF13/HeliconCorpFighterHF13Illumination.png")
    model:setScale(2)
    model:setRadius(50)

    model:addEngineEmitter(-0.75, 0.24,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.00,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.24,-0.1,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("HeliconCorpScoutHS9" .. color)
    model:setMesh("HeliconCorpScoutHS9/HeliconCorpScoutHS9Hull.obj")
    model:setTexture("HeliconCorpScoutHS9/HeliconCorpScoutHS9"..color.."Albedo.png")
    model:setSpecular("HeliconCorpScoutHS9/HeliconCorpScoutHS9Specular.png")
    model:setIllumination("HeliconCorpScoutHS9/HeliconCorpScoutHS9Illumination.png")
    model:setScale(2)
    model:setRadius(50)

    model:addEngineEmitter(-0.75, 0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.0,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
end

--Standard data
model = ModelData()
model:setName("space_station_4")
model:setMesh("space_station_4/space_station_4.model")
model:setTexture("space_station_4/space_station_4_color.jpg")
model:setSpecular("space_station_4/space_station_4_specular.jpg")
model:setIllumination("space_station_4/space_station_4_illumination.jpg")
model:setRenderOffset(0, 0, 5)
model:setScale(10)
model:setRadius(300)
model:setCollisionBox(400, 400)

model = ModelData()
model:setName("space_station_3")
model:setMesh("space_station_3/space_station_3.model")
model:setTexture("space_station_3/space_station_3_color.jpg")
model:setSpecular("space_station_3/space_station_3_specular.jpg")
model:setIllumination("space_station_3/space_station_3_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(20)
model:setRadius(1000)
model:setCollisionBox(1200, 1000)

model = ModelData()
model:setName("space_station_2")
model:setMesh("space_station_2/space_station_2.model")
model:setTexture("space_station_2/space_station_2_color.jpg")
model:setSpecular("space_station_2/space_station_2_specular.jpg")
model:setIllumination("space_station_2/space_station_2_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(20)
model:setRadius(1300)
model:setCollisionBox(1400, 1000)

model = ModelData()
model:setName("space_station_1")
model:setMesh("space_station_1/space_station_1.model")
model:setTexture("space_station_1/space_station_1_color.jpg")
model:setSpecular("space_station_1/space_station_1_specular.jpg")
model:setIllumination("space_station_1/space_station_1_illumination.jpg")
model:setRenderOffset(0, 0, 5)
model:setScale(20)
model:setRadius(1500)
model:setCollisionBox(2000, 1800)

model = ModelData()
model:setName("small_fighter_1")
model:setMesh("small_fighter_1.model")
model:setTexture("small_fighter_1_color.jpg")
model:setSpecular("small_fighter_1_specular.jpg")
model:setIllumination("small_fighter_1_illumination.jpg")
model:setScale(0.5)
model:setRadius(30)

-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(23, 0, -1.8)
model:addEngineEmitter(-8, 0, 0.5,  1.0, 0.2, 0.2, 1.5)


model = ModelData()
model:setName("space_tug")
model:setMesh("space_tug.model")
model:setTexture("space_tug_color.jpg")
--model:setSpecular("space_tug_illumination.jpg")
model:setIllumination("space_tug_illumination.jpg")
model:setScale(6)
model:setRadius(80)

model:addEngineEmitter(-13, -2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)
model:addEngineEmitter(-13,  2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)



model = ModelData()
model:setName("space_frigate_6")
model:setMesh("space_frigate_6.model")
model:setTexture("space_frigate_6_color.png")
model:setSpecular("space_frigate_6_specular.png")
model:setIllumination("space_frigate_6_illumination.png")
model:setScale(2)
model:setRadius(30)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(-1.6, -8, -2)
model:addBeamPosition(-1.6,  8, -2)
model:addTubePosition(18, 0, -3.5)
model:addTubePosition(18, 0, -3.5)
model:addEngineEmitter(-18, 0, -1,  0.2, 0.2, 1.0, 6.0)


model = ModelData()
model:setName("space_cruiser_4")
model:setMesh("space_cruiser_4.model")
model:setTexture("space_cruiser_4_color.jpg")
--model:setSpecular("space_cruiser_4_illumination.jpg")
model:setIllumination("space_cruiser_4_illumination.jpg")
model:setScale(8)
model:setRadius(100)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addTubePosition(2, -10, -2.3)
model:addTubePosition(2,  10, -2.3)
model:addEngineEmitter(-13, -2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)
model:addEngineEmitter(-13, 2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)

model = ModelData()
model:setName("dark_fighter_6")
model:setMesh("dark_fighter_6.model")
model:setTexture("dark_fighter_6_color.png")
model:setSpecular("dark_fighter_6_specular.png")
model:setIllumination("dark_fighter_6_illumination.png")
model:setScale(1)
model:setRadius(30)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(21, -28.2, -2)
model:addBeamPosition(21,  28.2, -2)
model:addEngineEmitter(-28, -1.5, -5,  1.0, 0.2, 0.2, 3.0)
model:addEngineEmitter(-28,  1.5, -5,  1.0, 0.2, 0.2, 3.0)


model = ModelData()
model:setName("battleship_destroyer_1_upgraded")
model:setMesh("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded.model")
model:setTexture("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(250)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(34, -17, -7)
model:addBeamPosition(34,  17, -7)
model:addBeamPosition(-5, -33, -1)
model:addBeamPosition(-5,  33, -1)
model:addTubePosition(5, -7, -11)
model:addTubePosition(5,  7, -11)
model:addEngineEmitter(-30, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33, 12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33,-12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33, 22, -1,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33,-22, -1,  1.0, 0.2, 0.1, 14.0)

model = ModelData()
model:setName("battleship_destroyer_2_upgraded")
model:setMesh("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded.model")
model:setTexture("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_illumination.jpg")
model:setScale(3)
model:setRadius(200)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(37, -14.5, -3.5)
model:addBeamPosition(37,  14.5, -3.5)
model:addBeamPosition(10, -12, -15)
model:addBeamPosition(10,  12, -15)
model:addBeamPosition(-9, -28, -3)
model:addBeamPosition(-9,  28, -3)
model:addEngineEmitter(-33, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 14, -4,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-14, -4,  1.0, 0.2, 0.1, 17.0)

model = ModelData()
model:setName("battleship_destroyer_3_upgraded")
model:setMesh("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded.model")
model:setTexture("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_illumination.jpg")
model:setScale(6)
model:setRadius(300)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(22,  22, -4.5)
model:addBeamPosition(22, -22, -4.5)
model:addBeamPosition(12,  22, -4.5)
model:addBeamPosition(12, -22, -4.5)

model:addEngineEmitter(-34, 0, 0,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 13, 0,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-13, 0,  1.0, 0.2, 0.1, 17.0)

model = ModelData()
model:setName("battleship_destroyer_4_upgraded")
model:setMesh("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded.model")
model:setTexture("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_illumination.jpg")
model:setScale(2)
model:setRadius(150)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(4, -27, -0.5)
model:addBeamPosition(4,  27, -0.5)
model:addTubePosition(30, -11, -0.5)
model:addTubePosition(30,  11, -0.5)
model:addEngineEmitter(-27, 0, -4,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-32, 11.5, -1.5,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-32,-11.5, -1.5,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-30, 20, -1.5,  1.0, 0.2, 0.1, 10.0)
model:addEngineEmitter(-32,-20, -1.5,  1.0, 0.2, 0.1, 10.0)

model = ModelData()
model:setName("battleship_destroyer_5_upgraded")
model:setMesh("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded.model")
model:setTexture("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_illumination.jpg")
model:setScale(3)
model:setRadius(200)

-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(4, -27, -0.5)
model:addBeamPosition(4,  27, -0.5)
model:addTubePosition(27, 0, -0.5)
model:addTubePosition(27, 0, -0.5)
model:addEngineEmitter(-33, 0, 0,  1.0, 0.2, 0.1, 16.0)
model:addEngineEmitter(-28, 13, -0,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-28,-13, -0,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-27, 24, 0,  1.0, 0.2, 0.1, 5.0)
model:addEngineEmitter(-27,-24, 0,  1.0, 0.2, 0.1, 5.0)

model = ModelData()
model:setName("sci_fi_alien_ship_1")
model:setMesh("sci_fi_alien_ship_1/sci_fi_alien_ship_1.model")
model:setTexture("sci_fi_alien_ship_1/sci_fi_alien_ship_1_color.jpg")
model:setSpecular("sci_fi_alien_ship_1/sci_fi_alien_ship_1_specular.jpg")
model:setIllumination("sci_fi_alien_ship_1/sci_fi_alien_ship_1_illumination.jpg")
model:setScale(3)
model:setRadius(180)

model = ModelData()
model:setName("sci_fi_alien_ship_2")
model:setMesh("sci_fi_alien_ship_2/sci_fi_alien_ship_2.model")
model:setTexture("sci_fi_alien_ship_2/sci_fi_alien_ship_2_color.jpg")
model:setSpecular("sci_fi_alien_ship_2/sci_fi_alien_ship_2_specular.jpg")
model:setIllumination("sci_fi_alien_ship_2/sci_fi_alien_ship_2_illumination.jpg")
model:setScale(3)
model:setRadius(180)

model = ModelData()
model:setName("sci_fi_alien_ship_3")
model:setMesh("sci_fi_alien_ship_3/sci_fi_alien_ship_3.model")
model:setTexture("sci_fi_alien_ship_3/sci_fi_alien_ship_3_color.jpg")
model:setSpecular("sci_fi_alien_ship_3/sci_fi_alien_ship_3_specular.jpg")
model:setIllumination("sci_fi_alien_ship_3/sci_fi_alien_ship_3_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_4")
model:setMesh("sci_fi_alien_ship_4/sci_fi_alien_ship_4.model")
model:setTexture("sci_fi_alien_ship_4/sci_fi_alien_ship_4_color.jpg")
model:setSpecular("sci_fi_alien_ship_4/sci_fi_alien_ship_4_specular.jpg")
model:setIllumination("sci_fi_alien_ship_4/sci_fi_alien_ship_4_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_5")
model:setMesh("sci_fi_alien_ship_5/sci_fi_alien_ship_5.model")
model:setTexture("sci_fi_alien_ship_5/sci_fi_alien_ship_5_color.jpg")
model:setSpecular("sci_fi_alien_ship_5/sci_fi_alien_ship_5_specular.jpg")
model:setIllumination("sci_fi_alien_ship_5/sci_fi_alien_ship_5_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_6")
model:setMesh("sci_fi_alien_ship_6/sci_fi_alien_ship_6.model")
model:setTexture("sci_fi_alien_ship_6/sci_fi_alien_ship_6_color.jpg")
model:setSpecular("sci_fi_alien_ship_6/sci_fi_alien_ship_6_specular.jpg")
model:setIllumination("sci_fi_alien_ship_6/sci_fi_alien_ship_6_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_7")
model:setMesh("sci_fi_alien_ship_7/sci_fi_alien_ship_7.model")
model:setTexture("sci_fi_alien_ship_7/sci_fi_alien_ship_7_color.jpg")
model:setSpecular("sci_fi_alien_ship_7/sci_fi_alien_ship_7_specular.jpg")
model:setIllumination("sci_fi_alien_ship_7/sci_fi_alien_ship_7_illumination.jpg")
model:setScale(6)
model:setRadius(330)

model = ModelData()
model:setName("sci_fi_alien_ship_8")
model:setMesh("sci_fi_alien_ship_8/sci_fi_alien_ship_8.model")
model:setTexture("sci_fi_alien_ship_8/sci_fi_alien_ship_8_color.jpg")
model:setSpecular("sci_fi_alien_ship_8/sci_fi_alien_ship_8_specular.jpg")
model:setIllumination("sci_fi_alien_ship_8/sci_fi_alien_ship_8_illumination.jpg")
model:setScale(6)
model:setRadius(350)

model = ModelData()
model:setName("ammo_box")
model:setRadius(50)
model:setMesh("ammo_box.obj")
model:setTexture("ammo_box.png")
model:setSpecular("ammo_box_specular.png")
model:setIllumination("ammo_box_illumination.png")

model = ModelData()
model:setName("shield_generator")
model:setRadius(150)
model:setScale(3)
model:setMesh("Shield bubble generator.obj")
model:setTexture("Shield bubble generator.jpg")
model:setSpecular("Shield bubble generator specular.jpg")

model = ModelData()
model:setName("small_frigate_1")
model:setMesh("small_frigate_1/small_frigate_1.model")
model:setTexture("small_frigate_1/small_frigate_1_color.png")
model:setSpecular("small_frigate_1/small_frigate_1_specular.png")
model:setIllumination("small_frigate_1/small_frigate_1_illumination.png")
model:setScale(0.8)
model:setRadius(200)

model:addEngineEmitter(-85, 33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85, 33, 14,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 14,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_2")
model:setMesh("small_frigate_2/small_frigate_2.model")
model:setTexture("small_frigate_2/small_frigate_2_color.png")
model:setSpecular("small_frigate_2/small_frigate_2_specular.png")
model:setIllumination("small_frigate_2/small_frigate_2_illumination.png")
model:setScale(1.8)
model:setRadius(300)

model:addEngineEmitter(-75, 53,-27,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-75,-53,-27,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_3")
model:setMesh("small_frigate_3/small_frigate_3.model")
model:setTexture("small_frigate_3/small_frigate_3_color.png")
model:setSpecular("small_frigate_3/small_frigate_3_specular.png")
model:setIllumination("small_frigate_3/small_frigate_3_illumination.png")
model:setScale(0.4)
model:setRadius(150)

model:addEngineEmitter(-91, 32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95, 32,-17,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-91,-32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95,-32,-17,  0.2, 0.2, 1.0, 8.0)
 
model = ModelData()
model:setName("small_frigate_4")
model:setMesh("small_frigate_4/small_frigate_4.model")
model:setTexture("small_frigate_4/small_frigate_4_color.png")
model:setSpecular("small_frigate_4/small_frigate_4_specular.png")
model:setIllumination("small_frigate_4/small_frigate_4_illumination.png")
model:setScale(0.8)
model:setRadius(200)

model:addEngineEmitter(-81, 10,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,  0,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,-10,-4,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_5")
model:setMesh("small_frigate_5/small_frigate_5.model")
model:setTexture("small_frigate_5/small_frigate_5_color.png")
model:setSpecular("small_frigate_5/small_frigate_5_specular.png")
model:setIllumination("small_frigate_5/small_frigate_5_illumination.png")
model:setScale(1.2)
model:setRadius(250)

model:addEngineEmitter(-95, 30, 8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95, 30, 0,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95, 30,-8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30, 8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30, 0,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30,-8,  0.2, 0.2, 1.0, 5.0)

for _, color in ipairs({"Blue", "Green", "Grey", "Red", "White", "Yellow"}) do
    model = ModelData()
    model:setName("AdlerLongRangeScout" .. color)
    model:setMesh("AdlerLongRangeScout/AdlerLongRangeSoutHull.model")
    model:setTexture("AdlerLongRangeScout/AlbedoAO/AdlerLongRangeScout"..color.."AlbedoAO.png")
    model:setSpecular("AdlerLongRangeScout/AdlerLongRangeScoutPBRSpecular.png")
    model:setIllumination("AdlerLongRangeScout/AdlerLongRangeScoutIllumination.png")
    model:setScale(95)
    model:setRadius(250)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)

    model = ModelData()
    model:setName("AtlasHeavyFighter" .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(130)
    model:setRadius(300)

    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("LindwurmFighter" .. color)
    model:setMesh("LindwurmFighter/LindwurmFighterHull.model")
    model:setTexture("LindwurmFighter/AlbedoAO/LindwurmFighter"..color.."AlbedoAO.png")
    model:setSpecular("LindwurmFighter/LindwurmFighterPBRSpecular.png")
    model:setIllumination("LindwurmFighter/LindwurmFighterIllumination.png")
    model:setScale(85)
    model:setRadius(200)
    model:addTubePosition(1.4, 0, 0.06)
    model:addTubePosition(0.3, 0.5, 0.06)
    model:addTubePosition(0.3,-0.5, 0.06)
    model:addEngineEmitter(-1, 0.54, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1,-0.54, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("WespeScout" .. color)
    model:setMesh("WespeScout/WespeScoutHull.model")
    model:setTexture("WespeScout/AlbedoAO/WespeScout"..color.."AlbedoAO.png")
    model:setSpecular("WespeScout/WespeScoutPBRSpecular.png")
    model:setIllumination("WespeScout/WespeScoutIllumination.png")
    model:setScale(60)
    model:setRadius(150)
    model:addBeamPosition(1.15, 0.13, -0.03)
    model:addBeamPosition(1.15,-0.13, -0.03)
    model:addEngineEmitter(-0.2, 0.44, -0.03,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-0.2,-0.44, -0.03,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("HeavyCorvette" .. color)
    model:setMesh("HeavyCorvette/HeavyCorvette.model")
    model:setTexture("HeavyCorvette/AlbedoAO/HeavyCorvette"..color.."AlbedoAO.png")
    model:setSpecular("HeavyCorvette/HeavyCorvettePBRSpecular.png")
    model:setIllumination("HeavyCorvette/HeavyCorvetteIllumination.png")
    model:setScale(120)
    model:setRadius(300)

    model:addEngineEmitter(-1.4, 0.4, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4, 0.0, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4,-0.4, 0.0,  0.5, 0.5, 1.0, 0.6)

    model = ModelData()
    model:setName("LaserCorvette" .. color)
    model:setMesh("LaserCorvette/LaserCorvette.model")
    model:setTexture("LaserCorvette/AlbedoAO/LaserCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LaserCorvette/LaserCorvettePBRSpecular.png")
    model:setIllumination("LaserCorvette/LaserCorvetteIllumination.png")
    model:setScale(90)
    model:setRadius(250)

    model:addEngineEmitter(-1.67, 0.1, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-1.67,-0.1, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("LightCorvette" .. color)
    model:setMesh("LightCorvette/LightCorvette.model")
    model:setTexture("LightCorvette/AlbedoAO/LightCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LightCorvette/LightCorvettePBRSpecular.png")
    model:setIllumination("LightCorvette/LightCorvetteIllumination.png")
    model:setScale(60)
    model:setRadius(150)

    model:addEngineEmitter(-1.3, 0.22, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3, 0.00, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3,-0.22, 0.15,  0.5, 0.5, 1.0, 0.3)

    model = ModelData()
    model:setName("MineLayerCorvette" .. color)
    model:setMesh("MineLayerCorvette/MineLayerCorvette.model")
    model:setTexture("MineLayerCorvette/AlbedoAO/MineLayerCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MineLayerCorvette/MineLayerCorvettePBRSpecular.png")
    model:setIllumination("MineLayerCorvette/MineLayerCorvetteIllumination.png")
    model:setScale(15)
    model:setRadius(80)

    model:addEngineEmitter(-0.65, 0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.65,-0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
	
	model = ModelData()
    model:setName("SpaceshipEscapePod" .. color)
    model:setMesh("SpaceshipEscapePod/SpaceshipEscapePod.obj")
    model:setTexture("SpaceshipEscapePod/SpaceshipEscapePod"..color.."Albedo.png")
   --model:setSpecular("MineLayerCorvette/MineLayerCorvettePBRSpecular.png")
    model:setIllumination("SpaceshipEscapePod/SpaceshipEscapePodIllumination.png")
    model:setScale(0.05)
    model:setRadius(40)

    model:addEngineEmitter(460.0, -410.0, -48.0,  0.0, 0.2, 1.0, 0.2)
   -- model:addEngineEmitter(-0.65,-0.70, 0.0,  0.0, 0.2, 1.0, 0.2)

    model = ModelData()
    model:setName("MissileCorvette" .. color)
    model:setMesh("MissileCorvette/MissileCorvette.model")
    model:setTexture("MissileCorvette/AlbedoAO/MissileCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MissileCorvette/MissileCorvettePBRSpecular.png")
    model:setIllumination("MissileCorvette/MissileCorvetteIllumination.png")
    model:setScale(85)
    model:setRadius(200)

    model:addEngineEmitter(-0.75, 0.24,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.00,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.24,-0.1,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("MultiGunCorvette" .. color)
    model:setMesh("MultiGunCorvette/MultiGunCorvette.model")
    model:setTexture("MultiGunCorvette/AlbedoAO/MultiGunCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MultiGunCorvette/MultiGunCorvettePBRSpecular.png")
    model:setIllumination("MultiGunCorvette/MultiGunCorvetteIllumination.png")
    model:setScale(75)
    model:setRadius(200)

    model:addEngineEmitter(-0.75, 0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.0,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
	
	
	model = ModelData()
    model:setName("TorpedoDestroyer" .. color)
    model:setMesh("TorpedoDestroyer/TorpedoDestroyer.obj")
    model:setTexture("TorpedoDestroyer/TorpedoDestroyer"..color.."AlbedoAO.png")
    model:setSpecular("TorpedoDestroyer/TorpedoDestroyerPBRSpecular.png")
    model:setIllumination("TorpedoDestroyer/TorpedoDestroyerIllumination.png")
    model:setScale(10)
    model:setRadius(200)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
	
		
	model = ModelData()
    model:setName("LightDestroyer" .. color)
    model:setMesh("LightDestroyer/LightDestroyer.obj")
    model:setTexture("LightDestroyer/LightDestroyer"..color.."AlbedoAO.png")
    model:setSpecular("LightDestroyer/LightDestroyerPBRSpecular.png")
    model:setIllumination("LightDestroyer/LightDestroyerIllumination.png")
    model:setScale(15)
    model:setRadius(250)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
	
	
	model = ModelData()
    model:setName("FlakDestroyer" .. color)
    model:setMesh("FlakDestroyer/FlakDestroyer.obj")
    model:setTexture("FlakDestroyer/FlakDestroyer"..color.."AlbedoAO.png")
    model:setSpecular("FlakDestroyer/FlakDestroyerPBRSpecular.png")
    model:setIllumination("FlakDestroyer/FlakDestroyerIllumination.png")
    model:setScale(5)
    model:setRadius(150)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
	
	model = ModelData()
    model:setName("HeavyDestroyer" .. color)
    model:setMesh("HeavyDestroyer/HeavyDestroyer.obj")
    model:setTexture("HeavyDestroyer/HeavyDestroyer"..color.."AlbedoAO.png")
    model:setSpecular("HeavyDestroyer/HeavyDestroyerPBRSpecular.png")
    model:setIllumination("HeavyDestroyer/HeavyDestroyerIllumination.png")
    model:setScale(20)
    model:setRadius(300)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
end

for _, color in ipairs({"Black", "Grey", "Blue", "Purple", "Red", "White"}) do
    model = ModelData()
    model:setName("ProgenitorFrigateA" .. color)
    model:setMesh("ProgenitorFrigates/ProgenitorFrigateA.obj")
    model:setTexture("ProgenitorFrigates/ProgenitorFrigateA"..color.."Albedo.png")
    model:setSpecular("ProgenitorFrigates/ProgenitorFrigateAPBRSpecular.png")
    model:setIllumination("ProgenitorFrigates/ProgenitorFrigateAIllumination.png")
    model:setScale(10)
    model:setRadius(150)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
	
	model = ModelData()
    model:setName("ProgenitorFrigateB" .. color)
    model:setMesh("ProgenitorFrigates/ProgenitorFrigateB.obj")
    model:setTexture("ProgenitorFrigates/ProgenitorFrigateB"..color.."Albedo.png")
    model:setSpecular("ProgenitorFrigates/ProgenitorFrigateBPBRSpecular.png")
    model:setIllumination("ProgenitorFrigates/ProgenitorFrigateBIllumination.png")
    model:setScale(10)
    model:setRadius(150)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)

    model = ModelData()
    model:setName("ProgenitorDestroyer" .. color)
    model:setMesh("ProgenitorDestroyer/ProgenitorDestroyer.obj")
    model:setTexture("ProgenitorDestroyer/ProgenitorDestroyer"..color.."Albedo.png")
    model:setSpecular("ProgenitorDestroyer/ProgenitorDestroyerPBRSpecular.png")
    model:setIllumination("ProgenitorDestroyer/ProgenitorDestroyerIllumination.png")
    model:setScale(3.2)
    model:setRadius(150)
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("ProgenitorCruiser" .. color)
    model:setMesh("ProgenitorCruiser/ProgenitorCruiser.obj")
    model:setTexture("ProgenitorCruiser/ProgenitorCruiser"..color.."Albedo.png")
    model:setSpecular("ProgenitorCruiser/ProgenitorCruiserPBRSpecular.png")
    model:setIllumination("ProgenitorCruiser/ProgenitorCruiserIllumination.png")
    model:setScale(2.4)
    model:setRadius(150)
    model:addTubePosition(1.4, 0, 0.06)
    model:addTubePosition(0.3, 0.5, 0.06)
    model:addTubePosition(0.3,-0.5, 0.06)
    model:addEngineEmitter(-1, 0.54, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1,-0.54, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("ProgenitorBattlecruiser" .. color)
    model:setMesh("ProgenitorBattlecruiser/ProgenitorBattlecruiser.obj")
    model:setTexture("ProgenitorBattlecruiser/ProgenitorBattlecruiser"..color.."Albedo.png")
    model:setSpecular("ProgenitorBattlecruiser/ProgenitorBattlecruiserPBRSpecular.png")
    model:setIllumination("ProgenitorBattlecruiser/ProgenitorBattlecruiserIllumination.png")
    model:setScale(3.4)
    model:setRadius(250)
    model:addBeamPosition(1.15, 0.13, -0.03)
    model:addBeamPosition(1.15,-0.13, -0.03)
    model:addEngineEmitter(-0.2, 0.44, -0.03,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-0.2,-0.44, -0.03,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("ProgenitorCarrier" .. color)
    model:setMesh("ProgenitorCarrier/ProgenitorCarrier.obj")
    model:setTexture("ProgenitorCarrier/ProgenitorCarrier"..color.."Albedo.png")
    model:setSpecular("ProgenitorCarrier/ProgenitorCarrierPBRSpecular.png")
    model:setIllumination("ProgenitorCarrier/ProgenitorCarrierIllumination.png")
    model:setScale(3.5)
    model:setRadius(300)
    model:addEngineEmitter(-1.67, 0.1, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-1.67,-0.1, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("ProgenitorBattleship" .. color)
    model:setMesh("ProgenitorBattleship/ProgenitorBattleshipHull.obj")
    model:setTexture("ProgenitorBattleship/ProgenitorBattleship"..color.."Albedo.png")
    model:setSpecular("ProgenitorBattleship/ProgenitorBattleshipPBRSpecular.png")
    model:setIllumination("ProgenitorBattleship/ProgenitorBattleshipIllumination.png")
    model:setScale(4)
    model:setRadius(300)
    model:addEngineEmitter(-1.3, 0.22, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3, 0.00, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3,-0.22, 0.15,  0.5, 0.5, 1.0, 0.3)

    model = ModelData()
    model:setName("ProgenitorBomber" .. color)
    model:setMesh("ProgenitorFighters/ProgenitorBomber.obj")
    model:setTexture("ProgenitorFighters/ProgenitorBomber"..color.."Albedo.png")
    model:setSpecular("ProgenitorFighters/ProgenitorBomberPBRSpecular.png")
    model:setIllumination("ProgenitorFighters/ProgenitorBomberIllumination.png")
    model:setScale(15)
    model:setRadius(60)
    model:addEngineEmitter(-0.65, 0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.65,-0.70, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("ProgenitorFighter" .. color)
    model:setMesh("ProgenitorFighters/ProgenitorFighter.obj")
    model:setTexture("ProgenitorFighters/ProgenitorFighter"..color.."Albedo.png")
    model:setSpecular("ProgenitorFighters/ProgenitorFighterPBRSpecular.png")
    model:setIllumination("ProgenitorFighters/ProgenitorFighterIllumination.png")
    model:setScale(15)
    model:setRadius(50)

    model:addEngineEmitter(-0.75, 0.24,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.00,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.24,-0.1,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("ProgenitorScout" .. color)
    model:setMesh("ProgenitorFighters/ProgenitorScout.obj")
    model:setTexture("ProgenitorFighters/ProgenitorScout"..color.."Albedo.png")
    model:setSpecular("ProgenitorFighters/ProgenitorScoutPBRSpecular.png")
    model:setIllumination("ProgenitorFighters/ProgenitorScoutIllumination.png")
    model:setScale(15)
    model:setRadius(50)

    model:addEngineEmitter(-0.75, 0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.0,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
	
	model = ModelData()
    model:setName("ProgenitorStation" .. color)
    model:setMesh("ProgenitorStation/ProgenitorStation.obj")
    model:setTexture("ProgenitorStation/ProgenitorStation"..color.."Albedo.png")
    model:setSpecular("ProgenitorStation/ProgenitorStationPBRSpecular.png")
    model:setIllumination("ProgenitorStation/ProgenitorStationIllumination.png")
    model:setScale(0.8)
    model:setRadius(350)
end

---- BUOYS

model = ModelData()
model:setName("SensorBuoyMKI")
model:setMesh("SensorBuoy/SensorBuoyMKI.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

model = ModelData()
model:setName("SensorBuoyMKII")
model:setMesh("SensorBuoy/SensorBuoyMKII.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

model = ModelData()
model:setName("SensorBuoyMKIII")
model:setMesh("SensorBuoy/SensorBuoyMKIII.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

for type=1,5 do
    for cnt=1,5 do
        model = ModelData():setName("transport_" .. type .. "_" .. cnt)
        model:setScale(0.5)
        model:setRadius(100 + cnt * 50)
        model:setCollisionBox(200 + cnt * 100, 200)
        model:setMesh("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_cargo_" .. cnt .. ".model")
        model:setTexture("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_color.png")
        model:setSpecular("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_specular.png")
        model:setIllumination("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_illumination.png")
    end
end

-- WRECKS AND ADDITIONAL "ARTIFACTS"

ModelData():setName("cargo"):setScale(1):setRadius(30):setMesh("cargo.obj"):setTexture("Military_Box_ao.png")

ModelData():setName("cargo-scanned"):setScale(10):setRadius(30):setMesh("cargo-scanned.obj"):setTexture("cargo-scanned.png")

ModelData():setName("cassard-wreck"):setScale(5):setRadius(150):setMesh("cassard-wreck.obj"):setTexture("FlakDestroyer/FlakDestroyerGreenAlbedo.png")

ModelData():setName("hoplite-wreck"):setScale(0.5):setRadius(150):setMesh("hoplite-wreck.obj"):setTexture("HeliconCorpBastionClassDestroyer/HeliconCorpBastionClassDestroyerBlueAlbedo.png")

ModelData():setName("vanguard-wreck"):setScale(1):setRadius(150):setMesh("vanguard-wreck.obj"):setTexture("HeliconCorpBruteClassFrigate/HeliconCorpBruteClassFrigateBlueAlbedo.png")

ModelData():setName("shuttle-wreck"):setScale(0.05):setRadius(40):setMesh("shuttle-wreck.obj"):setTexture("SpaceshipEscapePod/SpaceshipEscapePodBlueAlbedo.png")