    -- Name: BC Ship Sizes 2
-- Description:Tutorial scenario - refer to docs for deet
-- Type: Basic
    CpuShip():setFaction("Independent"):setTemplate("King George Battleship"):setCallSign("VK1"):setPosition(3293, -2022):setWeaponStorage("EMP", 6):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Mohondas Cruiser"):setCallSign("NC2"):setPosition(1070, -2024):setWeaponStorage("EMP", 2):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Talavaar Destroyer"):setCallSign("CV3"):setPosition(-1233, -2049):setWeaponStorage("Homing", 0):setWeaponStorage("HVLI", 12):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Tribal Frigate"):setCallSign("VK4"):setPosition(-3472, -2023):setWeaponStorage("Homing", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Zuckerberg Cruiser"):setCallSign("VK5"):setPosition(1053, -171):setWeaponStorage("EMP", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Bezos Battleship"):setCallSign("S6"):setPosition(3374, -339):setWeaponStorage("EMP", 12):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Ballmer Frigate"):setCallSign("CSS7"):setPosition(-3479, -53):setWeaponStorage("Homing", 4):setWeaponStorage("EMP", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Musk Destroyer"):setCallSign("NC8"):setPosition(-1276, -243):setWeaponStorage("EMP", 4):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Orlov Frigate"):setCallSign("VK9"):setPosition(-3551, 1567):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Zhengzhou Destroyer"):setCallSign("VK10"):setPosition(-1215, 1405):setWeaponStorage("Nuke", 0):setWeaponStorage("EMP", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Zedong Cruiser"):setCallSign("VK11"):setPosition(1149, 1502):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Lenin Battleship"):setCallSign("CV12"):setPosition(3395, 1489):setWeaponStorage("EMP", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Seydlitz Cruiser"):setCallSign("SS13"):setPosition(1243, 3369):setWeaponStorage("Homing", 36):setWeaponStorage("Nuke", 0):setWeaponStorage("EMP", 24):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Shasta Cruiser"):setCallSign("CSS14"):setPosition(1285, 4799):setWeaponStorage("EMP", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Tsunami Frigate"):setCallSign("S15"):setPosition(-3621, 4845):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Washington Battleship"):setCallSign("CV16"):setPosition(3501, 4720):setWeaponStorage("EMP", 2):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Merkel Battleship"):setCallSign("S17"):setPosition(3461, 3295):setWeaponStorage("Nuke", 0):setWeaponStorage("EMP", 28):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Cassard Frigate"):setCallSign("S18"):setPosition(-3544, 3161):setWeaponStorage("Homing", 5):setWeaponStorage("EMP", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Mirabello Destroyer"):setCallSign("SS19"):setPosition(-1193, 3172):setWeaponStorage("Homing", 14):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Chikuma Stealth Destroyer"):setCallSign("S22"):setPosition(-1161, 4830):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Skirmish Frigate"):setCallSign("NC23"):setPosition(-3044, -3718):setWeaponStorage("Homing", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Vanguard Frigate"):setCallSign("UTI24"):setPosition(-4414, -3674):setWeaponStorage("Homing", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Hoplite Destroyer"):setCallSign("S25"):setPosition(-1168, -3679):setWeaponStorage("Homing", 0):setWeaponStorage("HVLI", 12):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCN Shuttle"):setCallSign("VK26"):setPosition(-6960, -4057):setWeaponStorage("Homing", 2):setWeaponStorage("HVLI", 3):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Interceptor"):setCallSign("BR27"):setPosition(-6962, -3201):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Gunship"):setCallSign("CCN28"):setPosition(-6963, -2249):setWeaponStorage("HVLI", 1):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("Bomber"):setCallSign("S29"):setPosition(-6975, -1338):setWeaponStorage("Homing", 1):setWeaponStorage("HVLI", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Sword Cruiser"):setCallSign("SS29"):setPosition(1003, -3673):setWeaponStorage("EMP", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Colony Battlecruiser"):setCallSign("S30"):setPosition(3218, -3748):setWeaponStorage("EMP", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Charybdis Battlecruiser"):setCallSign("CCN31"):setPosition(3159, -5543):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Ebirah Frigate"):setCallSign("CSS32"):setPosition(-3084, -5670):setWeaponStorage("EMP", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Gunship"):setCallSign("CSS33"):setPosition(-6882, -6328):setWeaponStorage("HVLI", 3):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Interceptor"):setCallSign("CV34"):setPosition(-6858, -8288):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Bomber"):setCallSign("S35"):setPosition(-6868, -7275):setWeaponStorage("Homing", 3):setWeaponStorage("HVLI", 4):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Bomber"):setCallSign("BR36"):setPosition(-8330, -8330):setWeaponStorage("Homing", 3):setWeaponStorage("HVLI", 8):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Gunship"):setCallSign("CCN37"):setPosition(-8238, -7146):setWeaponStorage("HVLI", 3):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("UCS Interceptor"):setCallSign("UTI38"):setPosition(-8182, -6326):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Jormungandr Battleship"):setCallSign("VS39"):setPosition(4980, -5498):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Kraken Destroyer"):setCallSign("UTI40"):setPosition(-1240, -5720):setWeaponStorage("EMP", 1):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Ottoia Frigate"):setCallSign("UTI41"):setPosition(-4406, -5720):setWeaponStorage("EMP", 0):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Scylla Cruiser"):setCallSign("NC42"):setPosition(1055, -5442):setWeaponStorage("EMP", 16):setHeading(180):orderIdle()
    CpuShip():setFaction("Independent"):setTemplate("BRU Leviathan Carrier"):setCallSign("VK43"):setPosition(6677, -5624):setWeaponStorage("EMP", 14):setHeading(180):orderIdle()
