-- [[Attack Drones used by other factions]]

template = ShipTemplate():setName("Drone"):setClass("Starfighter", "Drone"):setModel("small_fighter_1")
template:setRadarTrace("radar_drone.png")
template:setDescription([[Attack drones are small fighter ships operated remotely, usually from a station or a larger ship. Compact and fragile, they are most effective in great numbers.]])
template:setHull(40)
template:setWarpSpeed(1000)
template:setShields(20)
template:setSpeed(100, 38, 25)
template:setBeam(0, 35, 0, 900, 5.0, 5.0)
template:setBeam(1, 90, 30, 500, 5.0, 5.0)
template:setBeam(2, 90, -35, 500, 5.0, 5.0)
template:setTubes(1, 15.0)
template:setWeaponStorage("Homing", 7)
template:setWeaponStorage("HVLI", 3)
template:setDefaultAI('fighter')

variation = template:copy("Heat Drone")
variation:setDescription([[Heat Drones operate remotely, usually from a larger ship or a station. They are equipped with heat weapons and EMP missiles, and are most effective at disabling spaceships.]])
variation:setBeam(0, 10, 0, 1000, 5.0, 5.0)
variation:setBeam(1, 90, 30, 800, 8.0, 5.0)
variation:setBeam(2, 90, -35, 800, 8.0, 5.0)
variation:setBeamWeaponDamageType(0, 3)
variation:setBeamWeaponDamageType(1, 2)
variation:setBeamWeaponDamageType(2, 2)
variation:setTubes(2, 15.0)
variation:setWeaponStorage("EMP", 8)