--[[                  Stations
These are templates for space stations.
----------------------------------------------------------]]

template = ShipTemplate():setName("Small Station"):setModel("space_station_4"):setType("station")
template:setDescription([[Stations of this size are often used as research outposts, listening stations, and refuelling checkpoints for smaller craft. Crews turn over frequently in a small station's cramped accommodatations, but they are useful for monitoring areas of space, and most factions place small stations in areas they wish to keep an eye on. They are lightly shielded and vulnerable to swarming assaults.]])
template:setHull(150)
template:setShields(300)
template:setRadarTrace("radartrace_smallstation.png")
-- template:setDockClasses("Starfighter", "Frigate")
template:setExternalDockClasses("Frigate")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Medium Station"):setModel("space_station_3"):setType("station")
template:setDescription([[Large enough to accommodate small crews for extended periods of times, stations of this size are often trading posts, refuelling bases, mining operations, and forward military bases. While their shields are strong, concerted attacks by many ships can bring them down quickly.]])
template:setHull(400)
template:setShields(800)
template:setRadarTrace("radartrace_mediumstation.png")
-- template:setDockClasses("Starfighter", "Frigate", "Destroyer")
template:setExternalDockClasses("Frigate", "Destroyer")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Large Station"):setModel("space_station_2"):setType("station")
template:setDescription([[These spaceborne communities are few and far between, but most factions have begun to establish such stations as an alternative to planet dwelling in the absence of a suitable world. Stations of this size can be military installations, commercial hubs, deep-space settlements, and small shipyards. Only a concentrated attack can penetrate a large station's shields, and its hull can withstand all but the most powerful weaponry.]])
template:setHull(500)
template:setShields(1000, 1000, 1000)
template:setRadarTrace("radartrace_largestation.png")
-- template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser")
template:setExternalDockClasses("Frigate", "Destroyer", "Cruiser")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Huge Station"):setModel("space_station_1"):setType("station")
template:setDescription([[The size of a sprawling town, only a handful of stations of this scale have been established, but each faction has at least one. Stations at this scale represent a faction's center of spaceborne power, and most have been converted from arkships. They serve many functions at once and represent an extensive investment of time, money, and labor. A huge station's shields and thick hull can keep it intact long enough for reinforcements to arrive, even when faced with an ongoing siege or massive, perfectly coordinated assault. The loss of such a station could permanently cripple a faction.]])
template:setHull(1000)
template:setShields(2000, 2000, 2000, 2000)
template:setRadarTrace("radartrace_hugestation.png")
-- template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser", "Battleship", "Carrier")
template:setExternalDockClasses("Frigate", "Destroyer", "Cruiser", "Battleship", "Carrier")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

--------------------- Custom Stations --------------

--template = ShipTemplate():setName("Fuel Refinery"):setModel("kece"):setType("station")
--template:setDescription([[Fuel Rod Refineries are precious resources to be guarded at all costs. They often have a plentiful supply of fuel so can fall victim to piracy, or be a primary target in a conflict]])
--template:setHull(400)
--template:setShields(800)
--template:setRadarTrace("radartrace_mediumstation.png")
--template:setDockClasses("Starfighter", "Frigate", "Destroyer")
--template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Asteroid Mining Station"):setModel("kono"):setType("station")
template:setDescription([[With no viable planet to draw minerals from, asteroid mining has become a major occupation of all the factions, providing much needed raw materials for repairs and new constructions. Asteroid mining bases tend to be sprawling affairs, often joining several sizeable asteroids together into one complex.]])
template:setHull(1000)
template:setShields(2000, 2000, 2000, 2000)
template:setRadarTrace("radartrace_hugestation.png")
--template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser", "Battleship")
template:setExternalDockClasses("Frigate", "Destroyer", "Cruiser", "Battleship")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Asteroid Mining Rig"):setModel("eezo"):setType("station")
template:setDescription([[Asteroid Mining rigs are the backbone of all factions resource gathering efforts. The technology is reliable and standardised, and each rig is mostly automated, requiring only a skeleton crew. The work can be isolating, but it is generally well rewarded.]])
template:setHull(150)
template:setShields(300)
template:setRadarTrace("radartrace_smallstation.png")
-- template:setDockClasses("Starfighter", "Frigate")
template:setExternalDockClasses("Frigate")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Wormhole Stabiliser"):setModel("wormhole-generator"):setType("station"):setRecorded(false)
template:setDescription([[All factions are pouring considerable resources into finding and stabilising natural Einstein-Rosen Bridge phenomena (wormholes to the layperson). These experimental pieces of technology allow naturally existing wormholes to be opened and stabilised long enough for objects to pass through them safely.]])
template:setHull(500)
template:setShields(1000, 1000, 1000)
template:setRadarTrace("radartrace_largestation.png")
-- template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser")
template:setExternalDockClasses("Frigate", "Destroyer", "Cruiser")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)

--template = ShipTemplate():setName("Brutal Station"):setModel("ProgenitorStationBlack"):setType("station"):setRecorded(false)
--template:setDescription([[These spaceborne communities are few and far between, but most factions have begun to establish such stations as an alternative to planet dwelling in the absence of a suitable world. Stations of this size can be military installations, commercial hubs, deep-space settlements, and small shipyards. Only a concentrated attack can penetrate a large station's shields, and its hull can withstand all but the most powerful weaponry.]])
--template:setHull(500)
--template:setShields(1000, 1000, 1000)
--template:setRadarTrace("radartrace_largestation.png")
--template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser", "Battleship", "Carrier")
--template:setSharesEnergyWithDocked(true)


--template = ShipTemplate():setName("Comms Relay"):setModel("sensor-buoy"):setType("station")
--template:setDescription([[All factions make use of the comms relay network to boost the signals of their fleets, hence they are regarded as strictly neutral territory and attacking one is prohibited under the laws of space]])
--template:setHull(150)
--template:setShields(300)
--template:setRadarTrace("radartrace_smallstation.png")
--template:setDockClasses("Starfighter", "Frigate")
--template:setSharesEnergyWithDocked(true)

template = ShipTemplate():setName("Wreck of the Potomac"):setModel("heresy-g"):setType("station"):setRecorded(false)
template:setDescription([[Before JASA disappearead, they were rumoured to be working on alternative propulsion technology. This ship, half-buried inside an asteroid, has all the visual indicators of JASA technology, and the ident identifies itself as the JASA stealth destroyer Potomac.]])
template:setHull(500)
template:setShields(1000, 1000, 1000)
template:setRadarTrace("radartrace_largestation.png")
-- template:setDockClasses("Starfighter", "Frigate", "Destroyer", "Cruiser")
template:setExternalDockClasses("Frigate", "Destroyer", "Cruiser")
template:setInternalDockClasses("Starfighter")
template:setSharesEnergyWithDocked(true)