--[[               Drones
bada bip, bada bop, whaddaya know?
----------------------------------------------------------]]
template = ShipTemplate():setName("Defence Drone"):setType("drone"):setClass("Drone", "Combat"):setModel("HeliconCorpFighterHF13Blue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Defence drone armed with Beam weapons and Missiles]])
template:setEnergyStorage(1000)
template:setHull(100)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 4)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("Powered Defence Drone"):setType("drone"):setClass("Drone", "Combat"):setModel("HeliconCorpFighterHF13Blue")
--template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Defence drone armed with Beam weapons and Missiles that has its own reactor, enabling it to operate independently for long periods of time]])
template:setEnergyStorage(1000)
template:setHull(100)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 4)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("Scout Drone"):setType("drone"):setClass("Drone", "Scout"):setModel("HeliconCorpScoutHS9Blue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Long range scout]])
template:setEnergyStorage(1000)
template:setHull(100)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("Mine Layer Drone"):setType("drone"):setClass("Drone", "Combat"):setModel("HeliconCorpBomberHB22Blue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Mine layer]])
template:setEnergyStorage(1000)
template:setHull(150)
template:setSpeed(40, 50, 20)
template:setCombatManeuver(400, 250)
template:setTubes(1, 15.0)
template:setTubeDirection(0, 180)
template:setWeaponStorage("Mine", 4)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("Nuclear Launch Drone"):setType("drone"):setClass("Drone", "Combat"):setModel("HeliconCorpBomberHB22Blue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Nuclear Launch Delivery System]])
template:setEnergyStorage(1000)
template:setHull(150)
template:setSpeed(40, 50, 20)
template:setCombatManeuver(400, 250)
template:setTubes(1, 15.0)
template:setWeaponStorage("Nuke", 1)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)