name: EE Builder

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  #linux:
  #  name: Linux
  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Dependencies
  #    run: |
  #      sudo apt-get update -qq

  #  - name: Checkout EmptyEpsilon
  #    uses: actions/checkout@v2
  #    with:
  #      path: EmptyEpsilon

  #  - name: Checkout SeriousProton
  #    uses: actions/checkout@v2
  #    with:
  #      repository: daid/SeriousProton
  #      path: SeriousProton
  #      ref: master

  #  - name: Build
  #    run: |
  #      mkdir _build_win32
  #      cd _build_win32
  #      cmake .. -G Ninja -DSERIOUS_PROTON_DIR=../SeriousProton -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw.toolchain -DCMAKE_BUILD_TYPE=RelWithDebInfo
  #      cmake ../EmptyEpsilon -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_TOOLCHAIN_FILE=../EmptyEpsilon/cmake/mingw.toolchain -DSERIOUS_PROTON_DIR=../SeriousProton -DWARNING_IS_ERROR=1

  macos:
    name: MacOS
    runs-on: macos-latest

    steps:
      - name: Dependencies
        run: |
          brew install cmake sdl2 ninja sfml glm libopusenc

          #- name: Checkout EmptyEpsilon
          #  uses: actions/checkout@v2
          #  with:
          #    path: EmptyEpsilon

      - name: Checkout SeriousProton
        uses: actions/checkout@v3
        with:
          repository: tdelc/SeriousProton
          path: SeriousProton
          ref: master/b068a01   # Force specific version of SeriousProton
          fetch-depth: 0        # Force specific version of SeriousProton

      - name: Build
        run: |
          mkdir -p _build_macos
          cd _build_macos
          cmake ../EmptyEpsilon -G Ninja -DSERIOUS_PROTON_DIR=../SeriousProton -DCMAKE_INSTALL_PREFIX=. -DWARNING_IS_ERROR=1
          ninja
          ninja install
