name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  ########################################
  # Linux
  ########################################

  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: ${{ false }} # TODO: Disabled

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install build-essential libsfml-dev cmake git libsdl2-dev mingw-w64 ninja-build p7zip-full unzip wget zip

    - name: Checkout EmptyEpsilon
      uses: actions/checkout@v3
      with:
        path: EmptyEpsilon

    - name: Checkout SeriousProton
      uses: actions/checkout@v3
      with:
        repository: tdelc/SeriousProton
        path: SeriousProton
        fetch-depth: 0

    - name: Switch to correct SeriousProton version
      run: |
        cd SeriousProton
        git checkout b068a01

    - name: Build
      run: |
        mkdir _build_linux
        cd _build_linux
        cmake ../EmptyEpsilon -DSERIOUS_PROTON_DIR=../SeriousProton
        make

    - name: Zip artifact for deployment
      if: ${{ false }} # TODO: Disabled
      run: |
        zip -r emptyepsilon-linux.zip _build_linux/*.deb

    - name: Publish
      if: ${{ false }} # TODO: Disabled
      uses: actions/upload-artifact@v4
      with:
        name: EmptyEpsilon (linux)
        path: emptyepsilon-linux.zip

  ########################################
  # Windows - Testing
  ########################################

  win32:
    name: Win32
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install build-essential libsfml-dev cmake git libsdl2-dev mingw-w64 ninja-build p7zip-full unzip wget zip

    - name: Checkout EmptyEpsilon
      uses: actions/checkout@v3
      with:
        path: EmptyEpsilon

    - name: Checkout SeriousProton
      uses: actions/checkout@v3
      with:
        repository: tdelc/SeriousProton
        path: SeriousProton
        fetch-depth: 0

    - name: Switch to correct SeriousProton version
      run: |
        cd SeriousProton
        git checkout b068a01

    - name: Build
      run: |
        mkdir _build_win32
        cd _build_win32
        cmake ../EmptyEpsilon -G Ninja -DSERIOUS_PROTON_DIR=../SeriousProton -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_TOOLCHAIN_FILE=../EmptyEpsilon/cmake/mingw.toolchain -DWARNING_IS_ERROR=1
        ninja package

  ########################################
  # macOS
  ########################################

  macos:
    name: macOS
    runs-on: macos-latest
    if: ${{ false }} # TODO: Disabled

    steps:
    - name: Dependencies
      run: |
        brew install cmake sdl2 ninja sfml glm libopusenc

    - name: Checkout EmptyEpsilon
      uses: actions/checkout@v3
      with:
        path: EmptyEpsilon

    - name: Checkout SeriousProton
      uses: actions/checkout@v3
      with:
        repository: tdelc/SeriousProton
        path: SeriousProton
        fetch-depth: 0

    - name: Switch to correct SeriousProton version
      run: |
        cd SeriousProton
        git checkout b068a01

    - name: Build
      run: |
        mkdir -p _build_macos
        cd _build_macos
        cmake ../EmptyEpsilon -G Ninja -DSERIOUS_PROTON_DIR=../SeriousProton -DCMAKE_INSTALL_PREFIX=. -DWARNING_IS_ERROR=1
        ninja
        ninja install

    - name: Zip artifact for deployment
      if: ${{ false }} # TODO: Disabled
      run: |
        zip -r emptyepsilon-macos.zip _build_macos/EmptyEpsilon.app

    - name: Publish
      if: ${{ false }} # TODO: Disabled
      uses: actions/upload-artifact@v4
      with:
        name: EmptyEpsilon (macOS)
        path: emptyepsilon-macos.zip
