name: EE Builder

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update -qq

    - name: Checkout EmptyEpsilon
      uses: actions/checkout@v2
      with:
        path: EmptyEpsilon

    - name: Checkout SeriousProton
      uses: actions/checkout@v2
      with:
        repository: daid/SeriousProton
        path: SeriousProton
        ref: master

    - name: Build
      run: |
        mkdir _build_win32
        cd _build_win32
        cmake .. -G Ninja -DSERIOUS_PROTON_DIR=../SeriousProton -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw.toolchain -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build . --target package
